// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO6rQRSbjMsSshnWOkB9pn1KAMsACQikc',
    appId: '1:448677778827:web:6e2fedf8c84954f4b1cb8e',
    messagingSenderId: '448677778827',
    projectId: 'flutter-us-app',
    authDomain: 'flutter-us-app.firebaseapp.com',
    storageBucket: 'flutter-us-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEphzAN0i487rPO09IkWJKgiq8nAtWb3Y',
    appId: '1:448677778827:android:95a7ca21805bfe6fb1cb8e',
    messagingSenderId: '448677778827',
    projectId: 'flutter-us-app',
    storageBucket: 'flutter-us-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZXuxW8rvIAC2Ngu0SJrDymtobmr3tEGk',
    appId: '1:448677778827:ios:9eee097d53402fe5b1cb8e',
    messagingSenderId: '448677778827',
    projectId: 'flutter-us-app',
    storageBucket: 'flutter-us-app.appspot.com',
    iosClientId: '448677778827-aqt7i3mdcc1rhvvrok99ulpkvea2guio.apps.googleusercontent.com',
    iosBundleId: 'com.example.usApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZXuxW8rvIAC2Ngu0SJrDymtobmr3tEGk',
    appId: '1:448677778827:ios:9ed7bda38c635882b1cb8e',
    messagingSenderId: '448677778827',
    projectId: 'flutter-us-app',
    storageBucket: 'flutter-us-app.appspot.com',
    iosClientId: '448677778827-cea2oe1m7k6k171svf7242v8qbo2mpdl.apps.googleusercontent.com',
    iosBundleId: 'com.example.usApp.RunnerTests',
  );
}
